//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 22.06.2012 16:57:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace NHinernateUnit
{

    /// <summary>
    /// There are no comments for WithoutResult.Department, WithoutResult in the schema.
    /// </summary>
    public partial class ProductListPriceHistory {

        private int _ProductID;

        private date _StartDate;

        private date _EndDate;
		
		private int _ListPrice;
		
		private date _ModifiedDate;
    

        public ProductListPriceHistory()
        {
			
        }

    
        /// <summary>
        /// There are no comments for ProductID in the schema.
        /// </summary>
        public virtual int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this._ProductID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for StartDate in the schema.
        /// </summary>
        public virtual date StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this._StartDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for EndDate in the schema.
        /// </summary>
        public virtual date EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this._EndDate = value;
            }
        }
		
		public virtual int ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this._ListPrice = value;
            }
        }
		
		public virtual date ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }
    }

}

