//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PayrollModel", "FK_Employee_Department", "Department", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PayrollModel.Department), "Employee", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PayrollModel.Employee))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PayrollModel", "FK_Employee_Designation", "Designation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PayrollModel.Designation), "Employee", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PayrollModel.Employee))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PayrollModel", "FK_Employee_ProvidentFund", "ProvidentFund", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PayrollModel.ProvidentFund), "Employee", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PayrollModel.Employee))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PayrollModel", "FK_Salary_Employee", "Employee", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PayrollModel.Employee), "Salary", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PayrollModel.Salary))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PayrollModel", "FK_Salary_ProvidentFund", "ProvidentFund", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PayrollModel.ProvidentFund), "Salary", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PayrollModel.Salary))]

// Original file name:
// Generation date: 11/23/2008 3:04:05 PM
namespace PayrollModel
{
    
    /// <summary>
    /// There are no comments for PayrollEntities in the schema.
    /// </summary>
    public partial class PayrollEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PayrollEntities object using the connection string found in the 'PayrollEntities' section of the application configuration file.
        /// </summary>
        public PayrollEntities() : 
                base("name=PayrollEntities", "PayrollEntities")
        {
        }
        /// <summary>
        /// Initialize a new PayrollEntities object.
        /// </summary>
        public PayrollEntities(string connectionString) : 
                base(connectionString, "PayrollEntities")
        {
        }
        /// <summary>
        /// Initialize a new PayrollEntities object.
        /// </summary>
        public PayrollEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PayrollEntities")
        {
        }
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Department> Department
        {
            get
            {
                if ((this._Department == null))
                {
                    this._Department = base.CreateQuery<Department>("[Department]");
                }
                return this._Department;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Department> _Department;
        /// <summary>
        /// There are no comments for Designation in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Designation> Designation
        {
            get
            {
                if ((this._Designation == null))
                {
                    this._Designation = base.CreateQuery<Designation>("[Designation]");
                }
                return this._Designation;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Designation> _Designation;
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Employee> Employee
        {
            get
            {
                if ((this._Employee == null))
                {
                    this._Employee = base.CreateQuery<Employee>("[Employee]");
                }
                return this._Employee;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Employee> _Employee;
        /// <summary>
        /// There are no comments for ProvidentFund in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<ProvidentFund> ProvidentFund
        {
            get
            {
                if ((this._ProvidentFund == null))
                {
                    this._ProvidentFund = base.CreateQuery<ProvidentFund>("[ProvidentFund]");
                }
                return this._ProvidentFund;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProvidentFund> _ProvidentFund;
        /// <summary>
        /// There are no comments for Salary in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Salary> Salary
        {
            get
            {
                if ((this._Salary == null))
                {
                    this._Salary = base.CreateQuery<Salary>("[Salary]");
                }
                return this._Salary;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Salary> _Salary;
        /// <summary>
        /// There are no comments for OldEmployeesSet in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<OldEmployees> OldEmployeesSet
        {
            get
            {
                if ((this._OldEmployeesSet == null))
                {
                    this._OldEmployeesSet = base.CreateQuery<OldEmployees>("[OldEmployeesSet]");
                }
                return this._OldEmployeesSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OldEmployees> _OldEmployeesSet;
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        public void AddToDepartment(Department department)
        {
            base.AddObject("Department", department);
        }
        /// <summary>
        /// There are no comments for Designation in the schema.
        /// </summary>
        public void AddToDesignation(Designation designation)
        {
            base.AddObject("Designation", designation);
        }
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
        /// <summary>
        /// There are no comments for ProvidentFund in the schema.
        /// </summary>
        public void AddToProvidentFund(ProvidentFund providentFund)
        {
            base.AddObject("ProvidentFund", providentFund);
        }
        /// <summary>
        /// There are no comments for Salary in the schema.
        /// </summary>
        public void AddToSalary(Salary salary)
        {
            base.AddObject("Salary", salary);
        }
        /// <summary>
        /// There are no comments for OldEmployeesSet in the schema.
        /// </summary>
        public void AddToOldEmployeesSet(OldEmployees oldEmployees)
        {
            base.AddObject("OldEmployeesSet", oldEmployees);
        }
        /// <summary>
        /// There are no comments for PayrollModel.GetOldEmployees in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<OldEmployees> GetOldEmployees()
        {
            return base.ExecuteFunction<OldEmployees>("GetOldEmployees");
        }
    }
    /// <summary>
    /// There are no comments for PayrollModel.OldEmployees in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PayrollModel", Name="OldEmployees")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class OldEmployees : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OldEmployees object.
        /// </summary>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        public static OldEmployees CreateOldEmployees(int employeeID)
        {
            OldEmployees oldEmployees = new OldEmployees();
            oldEmployees.EmployeeID = employeeID;
            return oldEmployees;
        }
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this.ReportPropertyChanging("EmployeeID");
                this._EmployeeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeID");
                this.OnEmployeeIDChanged();
            }
        }
        private int _EmployeeID;
        partial void OnEmployeeIDChanging(int value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private global::System.Nullable<int> _FirstName;
        partial void OnFirstNameChanging(global::System.Nullable<int> value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private global::System.Nullable<int> _LastName;
        partial void OnLastNameChanging(global::System.Nullable<int> value);
        partial void OnLastNameChanged();
    }
    /// <summary>
    /// There are no comments for PayrollModel.Department in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DepartmentID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PayrollModel", Name="Department")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Department : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="departmentID">Initial value of DepartmentID.</param>
        /// <param name="departmentName">Initial value of DepartmentName.</param>
        /// <param name="departmentHead">Initial value of DepartmentHead.</param>
        public static Department CreateDepartment(long departmentID, string departmentName, long departmentHead)
        {
            Department department = new Department();
            department.DepartmentID = departmentID;
            department.DepartmentName = departmentName;
            department.DepartmentHead = departmentHead;
            return department;
        }
        /// <summary>
        /// There are no comments for Property DepartmentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long DepartmentID
        {
            get
            {
                return this._DepartmentID;
            }
            set
            {
                this.OnDepartmentIDChanging(value);
                this.ReportPropertyChanging("DepartmentID");
                this._DepartmentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DepartmentID");
                this.OnDepartmentIDChanged();
            }
        }
        private long _DepartmentID;
        partial void OnDepartmentIDChanging(long value);
        partial void OnDepartmentIDChanged();
        /// <summary>
        /// There are no comments for Property DepartmentName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName
        {
            get
            {
                return this._DepartmentName;
            }
            set
            {
                this.OnDepartmentNameChanging(value);
                this.ReportPropertyChanging("DepartmentName");
                this._DepartmentName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("DepartmentName");
                this.OnDepartmentNameChanged();
            }
        }
        private string _DepartmentName;
        partial void OnDepartmentNameChanging(string value);
        partial void OnDepartmentNameChanged();
        /// <summary>
        /// There are no comments for Property DepartmentHead in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long DepartmentHead
        {
            get
            {
                return this._DepartmentHead;
            }
            set
            {
                this.OnDepartmentHeadChanging(value);
                this.ReportPropertyChanging("DepartmentHead");
                this._DepartmentHead = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DepartmentHead");
                this.OnDepartmentHeadChanged();
            }
        }
        private long _DepartmentHead;
        partial void OnDepartmentHeadChanging(long value);
        partial void OnDepartmentHeadChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Employee_Department", "Employee")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Employee> Employee
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Employee>("PayrollModel.FK_Employee_Department", "Employee");
            }
        }
    }
    /// <summary>
    /// There are no comments for PayrollModel.Designation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DesignationID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PayrollModel", Name="Designation")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Designation : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Designation object.
        /// </summary>
        /// <param name="designationID">Initial value of DesignationID.</param>
        /// <param name="designationName">Initial value of DesignationName.</param>
        public static Designation CreateDesignation(long designationID, string designationName)
        {
            Designation designation = new Designation();
            designation.DesignationID = designationID;
            designation.DesignationName = designationName;
            return designation;
        }
        /// <summary>
        /// There are no comments for Property DesignationID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long DesignationID
        {
            get
            {
                return this._DesignationID;
            }
            set
            {
                this.OnDesignationIDChanging(value);
                this.ReportPropertyChanging("DesignationID");
                this._DesignationID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DesignationID");
                this.OnDesignationIDChanged();
            }
        }
        private long _DesignationID;
        partial void OnDesignationIDChanging(long value);
        partial void OnDesignationIDChanged();
        /// <summary>
        /// There are no comments for Property DesignationName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DesignationName
        {
            get
            {
                return this._DesignationName;
            }
            set
            {
                this.OnDesignationNameChanging(value);
                this.ReportPropertyChanging("DesignationName");
                this._DesignationName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("DesignationName");
                this.OnDesignationNameChanged();
            }
        }
        private string _DesignationName;
        partial void OnDesignationNameChanging(string value);
        partial void OnDesignationNameChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Employee_Designation", "Employee")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Employee> Employee
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Employee>("PayrollModel.FK_Employee_Designation", "Employee");
            }
        }
    }
    /// <summary>
    /// There are no comments for PayrollModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmployeeID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PayrollModel", Name="Employee")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Employee : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="phone">Initial value of Phone.</param>
        /// <param name="joiningDate">Initial value of JoiningDate.</param>
        public static Employee CreateEmployee(long employeeID, string firstName, string lastName, string address, string phone, global::System.DateTime joiningDate)
        {
            Employee employee = new Employee();
            employee.EmployeeID = employeeID;
            employee.FirstName = firstName;
            employee.LastName = lastName;
            employee.Address = address;
            employee.Phone = phone;
            employee.JoiningDate = joiningDate;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this.ReportPropertyChanging("EmployeeID");
                this._EmployeeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeID");
                this.OnEmployeeIDChanged();
            }
        }
        private long _EmployeeID;
        partial void OnEmployeeIDChanging(long value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property JoiningDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime JoiningDate
        {
            get
            {
                return this._JoiningDate;
            }
            set
            {
                this.OnJoiningDateChanging(value);
                this.ReportPropertyChanging("JoiningDate");
                this._JoiningDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("JoiningDate");
                this.OnJoiningDateChanged();
            }
        }
        private global::System.DateTime _JoiningDate;
        partial void OnJoiningDateChanging(global::System.DateTime value);
        partial void OnJoiningDateChanged();
        /// <summary>
        /// There are no comments for Property LeavingDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LeavingDate
        {
            get
            {
                return this._LeavingDate;
            }
            set
            {
                this.OnLeavingDateChanging(value);
                this.ReportPropertyChanging("LeavingDate");
                this._LeavingDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("LeavingDate");
                this.OnLeavingDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LeavingDate;
        partial void OnLeavingDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLeavingDateChanged();
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Employee_Department", "Department")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Department Department
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("PayrollModel.FK_Employee_Department", "Department").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("PayrollModel.FK_Employee_Department", "Department").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("PayrollModel.FK_Employee_Department", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Department>("PayrollModel.FK_Employee_Department", "Department", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Designation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Employee_Designation", "Designation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Designation Designation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Designation>("PayrollModel.FK_Employee_Designation", "Designation").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Designation>("PayrollModel.FK_Employee_Designation", "Designation").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Designation in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Designation> DesignationReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Designation>("PayrollModel.FK_Employee_Designation", "Designation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Designation>("PayrollModel.FK_Employee_Designation", "Designation", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProvidentFund in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Employee_ProvidentFund", "ProvidentFund")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public ProvidentFund ProvidentFund
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProvidentFund>("PayrollModel.FK_Employee_ProvidentFund", "ProvidentFund").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProvidentFund>("PayrollModel.FK_Employee_ProvidentFund", "ProvidentFund").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ProvidentFund in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<ProvidentFund> ProvidentFundReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProvidentFund>("PayrollModel.FK_Employee_ProvidentFund", "ProvidentFund");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ProvidentFund>("PayrollModel.FK_Employee_ProvidentFund", "ProvidentFund", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Salary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Salary_Employee", "Salary")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Salary> Salary
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Salary>("PayrollModel.FK_Salary_Employee", "Salary");
            }
        }
    }
    /// <summary>
    /// There are no comments for PayrollModel.ProvidentFund in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PFID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PayrollModel", Name="ProvidentFund")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class ProvidentFund : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProvidentFund object.
        /// </summary>
        /// <param name="pFID">Initial value of PFID.</param>
        /// <param name="employeeID">Initial value of EmployeeID.</param>
        /// <param name="pFAmount">Initial value of PFAmount.</param>
        public static ProvidentFund CreateProvidentFund(long pFID, long employeeID, decimal pFAmount)
        {
            ProvidentFund providentFund = new ProvidentFund();
            providentFund.PFID = pFID;
            providentFund.EmployeeID = employeeID;
            providentFund.PFAmount = pFAmount;
            return providentFund;
        }
        /// <summary>
        /// There are no comments for Property PFID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long PFID
        {
            get
            {
                return this._PFID;
            }
            set
            {
                this.OnPFIDChanging(value);
                this.ReportPropertyChanging("PFID");
                this._PFID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PFID");
                this.OnPFIDChanged();
            }
        }
        private long _PFID;
        partial void OnPFIDChanging(long value);
        partial void OnPFIDChanged();
        /// <summary>
        /// There are no comments for Property EmployeeID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeID
        {
            get
            {
                return this._EmployeeID;
            }
            set
            {
                this.OnEmployeeIDChanging(value);
                this.ReportPropertyChanging("EmployeeID");
                this._EmployeeID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EmployeeID");
                this.OnEmployeeIDChanged();
            }
        }
        private long _EmployeeID;
        partial void OnEmployeeIDChanging(long value);
        partial void OnEmployeeIDChanged();
        /// <summary>
        /// There are no comments for Property PFAmount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PFAmount
        {
            get
            {
                return this._PFAmount;
            }
            set
            {
                this.OnPFAmountChanging(value);
                this.ReportPropertyChanging("PFAmount");
                this._PFAmount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4);
                this.ReportPropertyChanged("PFAmount");
                this.OnPFAmountChanged();
            }
        }
        private decimal _PFAmount;
        partial void OnPFAmountChanging(decimal value);
        partial void OnPFAmountChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Employee_ProvidentFund", "Employee")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Employee> Employee
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Employee>("PayrollModel.FK_Employee_ProvidentFund", "Employee");
            }
        }
        /// <summary>
        /// There are no comments for Salary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Salary_ProvidentFund", "Salary")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Salary> Salary
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Salary>("PayrollModel.FK_Salary_ProvidentFund", "Salary");
            }
        }
    }
    /// <summary>
    /// There are no comments for PayrollModel.Salary in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SalaryID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PayrollModel", Name="Salary")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Salary : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Salary object.
        /// </summary>
        /// <param name="salaryID">Initial value of SalaryID.</param>
        /// <param name="basic">Initial value of Basic.</param>
        /// <param name="allowance">Initial value of Allowance.</param>
        /// <param name="tax">Initial value of Tax.</param>
        /// <param name="grossSalary">Initial value of GrossSalary.</param>
        /// <param name="netSalary">Initial value of NetSalary.</param>
        public static Salary CreateSalary(long salaryID, decimal basic, decimal allowance, decimal tax, decimal grossSalary, decimal netSalary)
        {
            Salary salary = new Salary();
            salary.SalaryID = salaryID;
            salary.Basic = basic;
            salary.Allowance = allowance;
            salary.Tax = tax;
            salary.GrossSalary = grossSalary;
            salary.NetSalary = netSalary;
            return salary;
        }
        /// <summary>
        /// There are no comments for Property SalaryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SalaryID
        {
            get
            {
                return this._SalaryID;
            }
            set
            {
                this.OnSalaryIDChanging(value);
                this.ReportPropertyChanging("SalaryID");
                this._SalaryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SalaryID");
                this.OnSalaryIDChanged();
            }
        }
        private long _SalaryID;
        partial void OnSalaryIDChanging(long value);
        partial void OnSalaryIDChanged();
        /// <summary>
        /// There are no comments for Property Basic in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Basic
        {
            get
            {
                return this._Basic;
            }
            set
            {
                this.OnBasicChanging(value);
                this.ReportPropertyChanging("Basic");
                this._Basic = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4);
                this.ReportPropertyChanged("Basic");
                this.OnBasicChanged();
            }
        }
        private decimal _Basic;
        partial void OnBasicChanging(decimal value);
        partial void OnBasicChanged();
        /// <summary>
        /// There are no comments for Property Allowance in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Allowance
        {
            get
            {
                return this._Allowance;
            }
            set
            {
                this.OnAllowanceChanging(value);
                this.ReportPropertyChanging("Allowance");
                this._Allowance = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4);
                this.ReportPropertyChanged("Allowance");
                this.OnAllowanceChanged();
            }
        }
        private decimal _Allowance;
        partial void OnAllowanceChanging(decimal value);
        partial void OnAllowanceChanged();
        /// <summary>
        /// There are no comments for Property Tax in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tax
        {
            get
            {
                return this._Tax;
            }
            set
            {
                this.OnTaxChanging(value);
                this.ReportPropertyChanging("Tax");
                this._Tax = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4);
                this.ReportPropertyChanged("Tax");
                this.OnTaxChanged();
            }
        }
        private decimal _Tax;
        partial void OnTaxChanging(decimal value);
        partial void OnTaxChanged();
        /// <summary>
        /// There are no comments for Property GrossSalary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrossSalary
        {
            get
            {
                return this._GrossSalary;
            }
            set
            {
                this.OnGrossSalaryChanging(value);
                this.ReportPropertyChanging("GrossSalary");
                this._GrossSalary = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4);
                this.ReportPropertyChanged("GrossSalary");
                this.OnGrossSalaryChanged();
            }
        }
        private decimal _GrossSalary;
        partial void OnGrossSalaryChanging(decimal value);
        partial void OnGrossSalaryChanged();
        /// <summary>
        /// There are no comments for Property NetSalary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetSalary
        {
            get
            {
                return this._NetSalary;
            }
            set
            {
                this.OnNetSalaryChanging(value);
                this.ReportPropertyChanging("NetSalary");
                this._NetSalary = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4);
                this.ReportPropertyChanged("NetSalary");
                this.OnNetSalaryChanged();
            }
        }
        private decimal _NetSalary;
        partial void OnNetSalaryChanging(decimal value);
        partial void OnNetSalaryChanged();
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Salary_Employee", "Employee")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Employee Employee
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Employee>("PayrollModel.FK_Salary_Employee", "Employee").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Employee>("PayrollModel.FK_Salary_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Employee>("PayrollModel.FK_Salary_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Employee>("PayrollModel.FK_Salary_Employee", "Employee", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ProvidentFund in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PayrollModel", "FK_Salary_ProvidentFund", "ProvidentFund")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public ProvidentFund ProvidentFund
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProvidentFund>("PayrollModel.FK_Salary_ProvidentFund", "ProvidentFund").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProvidentFund>("PayrollModel.FK_Salary_ProvidentFund", "ProvidentFund").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ProvidentFund in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<ProvidentFund> ProvidentFundReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ProvidentFund>("PayrollModel.FK_Salary_ProvidentFund", "ProvidentFund");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ProvidentFund>("PayrollModel.FK_Salary_ProvidentFund", "ProvidentFund", value);
                }
            }
        }
    }
}
